# 临时运行配置：TCP + Admin 启用，匿名认证
[broker]
node_id = "lumenmq@dashboard-demo"
max_connections = 1000

[tcp]
enabled = true
bind = "0.0.0.0:1883"

[tls]
enabled = false

[websocket]
enabled = false

[mqtt_sn]
enabled = false

[auth]
mode = "anonymous"
allow_anonymous = true

[storage]
enabled = false

[log]
level = "info"
format = "compact"
dir = ""

[admin]
enabled = true
bind = "0.0.0.0:9090"

[security]
enabled = false

[plugin]
enabled = false
